import { BopProfile, CollegeYear } from "./types";

export const US_COLLEGES = [
  "Abilene Christian University",
  "Adelphi University",
  "Agnes Scott College",
  "Alabama A&M University",
  "Alabama State University",
  "Albany State University",
  "Albion College",
  "Alfred University",
  "Allegheny College",
  "American University",
  "Amherst College",
  "Anderson University",
  "Andrews University",
  "Angelo State University",
  "Antioch College",
  "Appalachian State University",
  "Arizona State University",
  "Arkansas State University",
  "Arkansas Tech University",
  "Assumption University",
  "Auburn University",
  "Augustana College",
  "Augustana University",
  "Austin College",
  "Austin Peay State University",
  "Babson College",
  "Ball State University",
  "Bard College",
  "Barnard College",
  "Barry University",
  "Bates College",
  "Baylor University",
  "Becker College",
  "Bellarmine University",
  "Bellevue College",
  "Belmont University",
  "Beloit College",
  "Bemidji State University",
  "Benedictine College",
  "Benedictine University",
  "Bennington College",
  "Bentley University",
  "Berea College",
  "Berklee College of Music",
  "Berry College",
  "Bethany College",
  "Bethel University",
  "Binghamton University, SUNY",
  "Biola University",
  "Birmingham-Southern College",
  "Black Hills State University",
  "Bloomsburg University of Pennsylvania",
  "Boise State University",
  "Boston College",
  "Boston University",
  "Bowdoin College",
  "Bowling Green State University",
  "Bradley University",
  "Brandeis University",
  "Bridgewater State University",
  "Brigham Young University",
  "Brigham Young University-Hawaii",
  "Brigham Young University-Idaho",
  "Brooklyn College, CUNY",
  "Brown University",
  "Bryant University",
  "Bryn Mawr College",
  "Bucknell University",
  "Butler University",
  "California Institute of Technology",
  "California Institute of the Arts",
  "California Lutheran University",
  "California Polytechnic State University, San Luis Obispo",
  "California State Polytechnic University, Pomona",
  "California State University, Bakersfield",
  "California State University, Channel Islands",
  "California State University, Chico",
  "California State University, Dominguez Hills",
  "California State University, East Bay",
  "California State University, Fresno",
  "California State University, Fullerton",
  "California State University, Long Beach",
  "California State University, Los Angeles",
  "California State University, Monterey Bay",
  "California State University, Northridge",
  "California State University, Sacramento",
  "California State University, San Bernardino",
  "California State University, San Marcos",
  "California State University, Stanislaus",
  "Calvin University",
  "Campbell University",
  "Canisius College",
  "Capital University",
  "Carleton College",
  "Carnegie Mellon University",
  "Carroll College",
  "Carroll University",
  "Case Western Reserve University",
  "Catholic University of America",
  "Cedarville University",
  "Centenary College of Louisiana",
  "Central Connecticut State University",
  "Central Michigan University",
  "Central Washington University",
  "Centre College",
  "Chapman University",
  "Charleston Southern University",
  "Chatham University",
  "Citadel Military College of South Carolina",
  "City College of New York, CUNY",
  "Claremont McKenna College",
  "Clarion University of Pennsylvania",
  "Clark Atlanta University",
  "Clark University",
  "Clarkson University",
  "Clemson University",
  "Cleveland State University",
  "Coastal Carolina University",
  "Coe College",
  "Colby College",
  "Colgate University",
  "College of Charleston",
  "College of Saint Benedict",
  "College of St. Scholastica",
  "College of the Holy Cross",
  "College of William & Mary",
  "College of Wooster",
  "Colorado College",
  "Colorado Mesa University",
  "Colorado School of Mines",
  "Colorado State University",
  "Columbia College Chicago",
  "Columbia University",
  "Concordia College",
  "Concordia University",
  "Connecticut College",
  "Cornell College",
  "Cornell University",
  "Creighton University",
  "Curry College",
  "Dartmouth College",
  "Davidson College",
  "Delaware State University",
  "Denison University",
  "DePaul University",
  "DePauw University",
  "Dickinson College",
  "Dillard University",
  "Dominican University",
  "Dominican University of California",
  "Drake University",
  "Drew University",
  "Drexel University",
  "Duke University",
  "Duquesne University",
  "Earlham College",
  "East Carolina University",
  "East Stroudsburg University of Pennsylvania",
  "East Tennessee State University",
  "Eastern Connecticut State University",
  "Eastern Illinois University",
  "Eastern Kentucky University",
  "Eastern Michigan University",
  "Eastern New Mexico University",
  "Eastern Washington University",
  "Eckerd College",
  "Edinboro University of Pennsylvania",
  "Elizabeth City State University",
  "Elizabethtown College",
  "Elmhurst University",
  "Elon University",
  "Emerson College",
  "Emmanuel College",
  "Emory University",
  "Emporia State University",
  "Endicott College",
  "Fairfield University",
  "Fairleigh Dickinson University",
  "Fayetteville State University",
  "Ferris State University",
  "Fisk University",
  "Fitchburg State University",
  "Florida A&M University",
  "Florida Atlantic University",
  "Florida Gulf Coast University",
  "Florida Institute of Technology",
  "Florida International University",
  "Florida Southern College",
  "Florida State University",
  "Fordham University",
  "Fort Hays State University",
  "Fort Lewis College",
  "Framingham State University",
  "Francis Marion University",
  "Franklin & Marshall College",
  "Franklin Pierce University",
  "Fresno Pacific University",
  "Furman University",
  "Gallaudet University",
  "Gannon University",
  "Gardner-Webb University",
  "George Fox University",
  "George Mason University",
  "George Washington University",
  "Georgetown University",
  "Georgia College & State University",
  "Georgia Institute of Technology",
  "Georgia Southern University",
  "Georgia State University",
  "Gettysburg College",
  "Gonzaga University",
  "Goucher College",
  "Grambling State University",
  "Grand Canyon University",
  "Grand Valley State University",
  "Grinnell College",
  "Grove City College",
  "Guilford College",
  "Gustavus Adolphus College",
  "Hamilton College",
  "Hamline University",
  "Hampden-Sydney College",
  "Hampshire College",
  "Hampton University",
  "Hanover College",
  "Harding University",
  "Harvard University",
  "Harvey Mudd College",
  "Haverford College",
  "Hawaii Pacific University",
  "High Point University",
  "Hillsdale College",
  "Hobart and William Smith Colleges",
  "Hofstra University",
  "Hollins University",
  "Holy Family University",
  "Hood College",
  "Hope College",
  "Houghton College",
  "Houston Baptist University",
  "Howard University",
  "Humboldt State University",
  "Hunter College, CUNY",
  "Idaho State University",
  "Illinois College",
  "Illinois Institute of Technology",
  "Illinois State University",
  "Illinois Wesleyan University",
  "Immaculata University",
  "Indiana State University",
  "Indiana University Bloomington",
  "Indiana University of Pennsylvania",
  "Indiana University-Purdue University Indianapolis",
  "Iona College",
  "Iowa State University",
  "Ithaca College",
  "Jackson State University",
  "Jacksonville State University",
  "Jacksonville University",
  "James Madison University",
  "John Carroll University",
  "Johns Hopkins University",
  "Johnson & Wales University",
  "Johnson C. Smith University",
  "Juniata College",
  "Kalamazoo College",
  "Kansas State University",
  "Kean University",
  "Keene State College",
  "Kennesaw State University",
  "Kent State University",
  "Kentucky State University",
  "Kenyon College",
  "Kettering University",
  "King's College",
  "Knox College",
  "Kutztown University of Pennsylvania",
  "La Salle University",
  "Lafayette College",
  "Lake Forest College",
  "Lamar University",
  "Lander University",
  "Langston University",
  "Lasell University",
  "Lawrence Technological University",
  "Lawrence University",
  "Le Moyne College",
  "Lebanon Valley College",
  "Lehigh University",
  "Lehman College, CUNY",
  "Lewis & Clark College",
  "Lewis University",
  "Liberty University",
  "Lincoln Memorial University",
  "Lincoln University",
  "Lindenwood University",
  "Linfield University",
  "Lipscomb University",
  "Lock Haven University",
  "Long Island University",
  "Longwood University",
  "Loras College",
  "Louisiana State University",
  "Louisiana Tech University",
  "Loyola Marymount University",
  "Loyola University Chicago",
  "Loyola University Maryland",
  "Loyola University New Orleans",
  "Luther College",
  "Lycoming College",
  "Lynn University",
  "Macalester College",
  "Maine Maritime Academy",
  "Manhattan College",
  "Manhattanville College",
  "Mansfield University of Pennsylvania",
  "Marian University",
  "Marist College",
  "Marquette University",
  "Marshall University",
  "Maryville University of Saint Louis",
  "Massachusetts College of Art and Design",
  "Massachusetts College of Liberal Arts",
  "Massachusetts Institute of Technology",
  "McDaniel College",
  "McGill University",
  "McKendree University",
  "McNeese State University",
  "Mercer University",
  "Mercyhurst University",
  "Merrimack College",
  "Messiah University",
  "Miami University",
  "Michigan State University",
  "Michigan Technological University",
  "Middle Tennessee State University",
  "Middlebury College",
  "Midwestern State University",
  "Millersville University of Pennsylvania",
  "Millikin University",
  "Mills College",
  "Millsaps College",
  "Minnesota State University, Mankato",
  "Minnesota State University, Moorhead",
  "Misericordia University",
  "Mississippi College",
  "Mississippi State University",
  "Mississippi University for Women",
  "Missouri State University",
  "Missouri University of Science and Technology",
  "Monmouth College",
  "Monmouth University",
  "Montana State University",
  "Montclair State University",
  "Moravian College",
  "Morehead State University",
  "Morehouse College",
  "Morgan State University",
  "Mount Holyoke College",
  "Mount St. Mary's University",
  "Muhlenberg College",
  "Murray State University",
  "Nazareth College",
  "Nebraska Wesleyan University",
  "New England College",
  "New England Institute of Technology",
  "New Jersey Institute of Technology",
  "New Mexico State University",
  "New York Institute of Technology",
  "New York University",
  "Niagara University",
  "Nicholls State University",
  "Nichols College",
  "Norfolk State University",
  "North Carolina A&T State University",
  "North Carolina Central University",
  "North Carolina State University",
  "North Dakota State University",
  "Northeastern Illinois University",
  "Northeastern State University",
  "Northeastern University",
  "Northern Arizona University",
  "Northern Illinois University",
  "Northern Kentucky University",
  "Northern Michigan University",
  "Northwest Missouri State University",
  "Northwestern State University of Louisiana",
  "Northwestern University",
  "Norwich University",
  "Nova Southeastern University",
  "Oakland University",
  "Oberlin College",
  "Occidental College",
  "Oglethorpe University",
  "Ohio Northern University",
  "Ohio State University",
  "Ohio University",
  "Ohio Wesleyan University",
  "Oklahoma City University",
  "Oklahoma State University",
  "Old Dominion University",
  "Olivet Nazarene University",
  "Oral Roberts University",
  "Oregon Institute of Technology",
  "Oregon State University",
  "Otterbein University",
  "Pace University",
  "Pacific Lutheran University",
  "Pacific University",
  "Palm Beach Atlantic University",
  "Parsons School of Design",
  "Pennsylvania State University",
  "Pepperdine University",
  "Pitzer College",
  "Plymouth State University",
  "Point Park University",
  "Pomona College",
  "Portland State University",
  "Prairie View A&M University",
  "Pratt Institute",
  "Presbyterian College",
  "Princeton University",
  "Providence College",
  "Purdue University",
  "Queens College, CUNY",
  "Queens University of Charlotte",
  "Quinnipiac University",
  "Radford University",
  "Ramapo College of New Jersey",
  "Randolph-Macon College",
  "Reed College",
  "Regis University",
  "Rensselaer Polytechnic Institute",
  "Rhode Island College",
  "Rhode Island School of Design",
  "Rhodes College",
  "Rice University",
  "Rider University",
  "Ripon College",
  "Rochester Institute of Technology",
  "Rockefeller University",
  "Roger Williams University",
  "Rollins College",
  "Roosevelt University",
  "Rose-Hulman Institute of Technology",
  "Rowan University",
  "Rutgers University",
  "Sacred Heart University",
  "Saginaw Valley State University",
  "Saint Anselm College",
  "Saint Francis University",
  "Saint John's University (MN)",
  "Saint Joseph's University",
  "Saint Leo University",
  "Saint Louis University",
  "Saint Mary's College",
  "Saint Mary's College of California",
  "Saint Mary's University of Minnesota",
  "Saint Michael's College",
  "Saint Peter's University",
  "Saint Vincent College",
  "Saint Xavier University",
  "Salem State University",
  "Salisbury University",
  "Salve Regina University",
  "Sam Houston State University",
  "Samford University",
  "San Diego State University",
  "San Francisco State University",
  "San Jose State University",
  "Santa Clara University",
  "Sarah Lawrence College",
  "Savannah College of Art and Design",
  "School of the Art Institute of Chicago",
  "Scripps College",
  "Seattle Pacific University",
  "Seattle University",
  "Seton Hall University",
  "Sewanee: The University of the South",
  "Shawnee State University",
  "Shenandoah University",
  "Shepherd University",
  "Shippensburg University of Pennsylvania",
  "Siena College",
  "Simmons University",
  "Simpson College",
  "Skidmore College",
  "Slippery Rock University of Pennsylvania",
  "Smith College",
  "Sonoma State University",
  "South Carolina State University",
  "South Dakota State University",
  "Southeast Missouri State University",
  "Southeastern Louisiana University",
  "Southeastern Oklahoma State University",
  "Southern Connecticut State University",
  "Southern Illinois University Carbondale",
  "Southern Illinois University Edwardsville",
  "Southern Methodist University",
  "Southern Nazarene University",
  "Southern New Hampshire University",
  "Southern Oregon University",
  "Southern Utah University",
  "Southwest Minnesota State University",
  "Southwestern University",
  "Spelman College",
  "Spring Hill College",
  "Springfield College",
  "St. Bonaventure University",
  "St. Catherine University",
  "St. Cloud State University",
  "St. Edward's University",
  "St. John Fisher College",
  "St. John's University (NY)",
  "St. Lawrence University",
  "St. Mary's University (TX)",
  "St. Olaf College",
  "Stanford University",
  "State University of New York at Albany",
  "State University of New York at Buffalo",
  "State University of New York at Geneseo",
  "State University of New York at New Paltz",
  "State University of New York at Oneonta",
  "State University of New York at Oswego",
  "State University of New York at Plattsburgh",
  "State University of New York at Potsdam",
  "State University of New York College at Brockport",
  "State University of New York College at Cortland",
  "State University of New York College at Fredonia",
  "State University of New York College of Environmental Science and Forestry",
  "Stephen F. Austin State University",
  "Stetson University",
  "Stevens Institute of Technology",
  "Stevenson University",
  "Stockton University",
  "Stonehill College",
  "Stony Brook University, SUNY",
  "Suffolk University",
  "Susquehanna University",
  "Swarthmore College",
  "Syracuse University",
  "Tarleton State University",
  "Temple University",
  "Tennessee State University",
  "Tennessee Technological University",
  "Texas A&M University",
  "Texas A&M University-Commerce",
  "Texas A&M University-Corpus Christi",
  "Texas A&M University-Kingsville",
  "Texas Christian University",
  "Texas Southern University",
  "Texas State University",
  "Texas Tech University",
  "Texas Woman's University",
  "The New School",
  "Thomas Jefferson University",
  "Towson University",
  "Transylvania University",
  "Trinity College",
  "Trinity University",
  "Troy University",
  "Truman State University",
  "Tufts University",
  "Tulane University",
  "Tuskegee University",
  "Union College (NY)",
  "Union University",
  "United States Air Force Academy",
  "United States Coast Guard Academy",
  "United States Merchant Marine Academy",
  "United States Military Academy",
  "United States Naval Academy",
  "University of Akron",
  "University of Alabama",
  "University of Alabama at Birmingham",
  "University of Alabama in Huntsville",
  "University of Alaska Anchorage",
  "University of Alaska Fairbanks",
  "University of Arizona",
  "University of Arkansas",
  "University of Arkansas at Little Rock",
  "University of Baltimore",
  "University of Bridgeport",
  "University of California, Berkeley",
  "University of California, Davis",
  "University of California, Irvine",
  "University of California, Los Angeles",
  "University of California, Merced",
  "University of California, Riverside",
  "University of California, San Diego",
  "University of California, San Francisco",
  "University of California, Santa Barbara",
  "University of California, Santa Cruz",
  "University of Central Arkansas",
  "University of Central Florida",
  "University of Central Missouri",
  "University of Central Oklahoma",
  "University of Charleston",
  "University of Chicago",
  "University of Cincinnati",
  "University of Colorado Boulder",
  "University of Colorado Colorado Springs",
  "University of Colorado Denver",
  "University of Connecticut",
  "University of Dallas",
  "University of Dayton",
  "University of Delaware",
  "University of Denver",
  "University of Detroit Mercy",
  "University of Evansville",
  "University of Florida",
  "University of Georgia",
  "University of Hartford",
  "University of Hawaii at Manoa",
  "University of Houston",
  "University of Idaho",
  "University of Illinois at Chicago",
  "University of Illinois at Springfield",
  "University of Illinois at Urbana-Champaign",
  "University of Indianapolis",
  "University of Iowa",
  "University of Kansas",
  "University of Kentucky",
  "University of La Verne",
  "University of Louisiana at Lafayette",
  "University of Louisiana at Monroe",
  "University of Louisville",
  "University of Maine",
  "University of Mary Washington",
  "University of Maryland, Baltimore County",
  "University of Maryland, College Park",
  "University of Massachusetts Amherst",
  "University of Massachusetts Boston",
  "University of Massachusetts Dartmouth",
  "University of Massachusetts Lowell",
  "University of Memphis",
  "University of Miami",
  "University of Michigan",
  "University of Michigan-Dearborn",
  "University of Minnesota Duluth",
  "University of Minnesota Twin Cities",
  "University of Mississippi",
  "University of Missouri",
  "University of Missouri-Kansas City",
  "University of Missouri-St. Louis",
  "University of Montana",
  "University of Montevallo",
  "University of Nebraska at Kearney",
  "University of Nebraska at Omaha",
  "University of Nebraska-Lincoln",
  "University of Nevada, Las Vegas",
  "University of Nevada, Reno",
  "University of New England",
  "University of New Hampshire",
  "University of New Haven",
  "University of New Mexico",
  "University of New Orleans",
  "University of North Alabama",
  "University of North Carolina at Asheville",
  "University of North Carolina at Chapel Hill",
  "University of North Carolina at Charlotte",
  "University of North Carolina at Greensboro",
  "University of North Carolina at Pembroke",
  "University of North Carolina at Wilmington",
  "University of North Dakota",
  "University of North Florida",
  "University of North Georgia",
  "University of North Texas",
  "University of Northern Colorado",
  "University of Northern Iowa",
  "University of Notre Dame",
  "University of Oklahoma",
  "University of Oregon",
  "University of Pennsylvania",
  "University of Pittsburgh",
  "University of Portland",
  "University of Puget Sound",
  "University of Redlands",
  "University of Rhode Island",
  "University of Richmond",
  "University of Rochester",
  "University of San Diego",
  "University of San Francisco",
  "University of Scranton",
  "University of South Alabama",
  "University of South Carolina",
  "University of South Dakota",
  "University of South Florida",
  "University of Southern California",
  "University of Southern Maine",
  "University of Southern Mississippi",
  "University of St. Thomas (MN)",
  "University of Tampa",
  "University of Tennessee at Chattanooga",
  "University of Tennessee, Knoxville",
  "University of Texas at Arlington",
  "University of Texas at Austin",
  "University of Texas at Dallas",
  "University of Texas at El Paso",
  "University of Texas at San Antonio",
  "University of Texas Rio Grande Valley",
  "University of the Pacific",
  "University of Toledo",
  "University of Tulsa",
  "University of Utah",
  "University of Vermont",
  "University of Virginia",
  "University of Washington",
  "University of West Florida",
  "University of West Georgia",
  "University of Wisconsin-Eau Claire",
  "University of Wisconsin-La Crosse",
  "University of Wisconsin-Madison",
  "University of Wisconsin-Milwaukee",
  "University of Wisconsin-Oshkosh",
  "University of Wisconsin-Stevens Point",
  "University of Wisconsin-Whitewater",
  "University of Wyoming",
  "Upper Iowa University",
  "Ursinus College",
  "Utah State University",
  "Utah Valley University",
  "Valdosta State University",
  "Valparaiso University",
  "Vanderbilt University",
  "Vassar College",
  "Villanova University",
  "Virginia Commonwealth University",
  "Virginia Military Institute",
  "Virginia Polytechnic Institute and State University",
  "Virginia State University",
  "Wabash College",
  "Wagner College",
  "Wake Forest University",
  "Wartburg College",
  "Washburn University",
  "Washington and Lee University",
  "Washington State University",
  "Washington University in St. Louis",
  "Wayne State College",
  "Wayne State University",
  "Weber State University",
  "Webster University",
  "Wellesley College",
  "Wesleyan University",
  "West Chester University of Pennsylvania",
  "West Texas A&M University",
  "West Virginia University",
  "Western Carolina University",
  "Western Connecticut State University",
  "Western Illinois University",
  "Western Kentucky University",
  "Western Michigan University",
  "Western New England University",
  "Western Oregon University",
  "Western Washington University",
  "Westfield State University",
  "Westminster College (PA)",
  "Westminster College (UT)",
  "Wheaton College (IL)",
  "Wheaton College (MA)",
  "Whitman College",
  "Whittier College",
  "Whitworth University",
  "Wichita State University",
  "Widener University",
  "Wilkes University",
  "Willamette University",
  "William Paterson University of New Jersey",
  "Williams College",
  "Winona State University",
  "Winthrop University",
  "Wofford College",
  "Worcester Polytechnic Institute",
  "Worcester State University",
  "Wright State University",
  "Xavier University",
  "Xavier University of Louisiana",
  "Yale University",
  "Yeshiva University",
  "York College of Pennsylvania",
  "Youngstown State University"
].sort();

export const MOCK_BOPS: BopProfile[] = [
  {
    id: '1',
    name: 'Tyler Durden',
    school: 'University of California, Los Angeles',
    year: CollegeYear.JUNIOR,
    imageUrl: 'https://picsum.photos/400/400?random=1',
    rating: 9.5, // BOP!
    voteCount: 24,
    totalScore: 228, // 9.5 * 24
    description: 'Always talking about some fight club. Has immaculate vibes though.',
    createdAt: Date.now(),
  },
  {
    id: '2',
    name: 'Jessica Day',
    school: 'New York University',
    year: CollegeYear.SENIOR,
    imageUrl: 'https://picsum.photos/400/400?random=2',
    rating: 2.2, // ANGEL
    voteCount: 15,
    totalScore: 33, // 2.2 * 15
    description: 'Literally the sun in human form. Bakes cookies for the dorm.',
    createdAt: Date.now() - 100000,
  },
  {
    id: '3',
    name: 'Chad Thundercock',
    school: 'Arizona State University',
    year: CollegeYear.SOPHOMORE,
    imageUrl: 'https://picsum.photos/400/400?random=3',
    rating: 5.5, // MEH
    voteCount: 8,
    totalScore: 44, // 5.5 * 8
    description: 'Needs to stop wearing sunglasses indoors. But he pays for drinks.',
    createdAt: Date.now() - 200000,
  },
  {
    id: '4',
    name: 'Hermione G.',
    school: 'Harvard University',
    year: CollegeYear.GRAD,
    imageUrl: 'https://picsum.photos/400/400?random=4',
    rating: 1.0, // SAINT
    voteCount: 50,
    totalScore: 50, // 1.0 * 50
    description: 'Academic weapon. Library vibes are unmatched. Pure soul.',
    createdAt: Date.now() - 300000,
  }
];